name: OnPush CI
on: push

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git branch
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Lint Typecript and templates
        run: npm run lint

      - name: Lint styles
        run: npm run lint:styles

      - name: Test
        run: npm run test
