name: Deploy CI
on: push
  # On push directly or by merging branch with pull request
  # push:
    # branches:
      # - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git branch
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Lint Typecript and templates
        run: npm run lint

      - name: Lint styles
        run: npm run lint:styles

      - name: Test
        run: npm run test

  dockerize:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git branch
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata for Docker
        # id: meta
        # uses: docker/metadata-action@v3
        # with:
          # images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.DEPLOY_WEBHOOK_URL }}
